dist: trusty
language: node_js
node_js: 
  - 8
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn
install: true
script: jest --coverage --coverageReporters=text-lcov | coveralls