import { Notebook as INotebook } from "@microsoft/microsoft-graph-types/microsoft-graph";

/**
 * Used in the DetailsList inside NotebookPicker
 * @export
 * @class NotebookRow
 */
export class NotebookRow {
  public fileName?: string;
  public notebook: INotebook;

  /**
   * The random string generated by the Microsoft Graph which represents the user
   */
  public userId: string;

  /**
   * The clean user id - i.e. email address
   */
  public userDisplayableId: string;
  public lastModifiedDateTime: Date;
  public id: string;

  constructor(notebook: INotebook, userId: string, displayableId: string) {
    this.fileName = notebook.displayName;
    this.lastModifiedDateTime = new Date(
      notebook.lastModifiedDateTime as string
    );
    this.userDisplayableId = displayableId;
    this.userId = userId;
    this.notebook = notebook;
  }
}
