// Users
export const AUTHENTICATE = "AUTHENTICATE";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const NEW_USER_OBJECT = "NEW_USER_OBJECT";
export const UPDATE_USER = "UPDATE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_PHOTO = "GET_PHOTO";
export const REAUTHORIZE_USER = "REAUTHORIZE_USER";

// Notebooks
export const GET_ALL_NOTEBOOKS = "GET_ALL_NOTEBOOKS";
export const PUT_ALL_NOTEBOOKS = "PUT_ALL_NOTEBOOKS";
export const CLEAR_ALL_NOTEBOOKS = "CLEAR_ALL_NOTEBOOKS";
export const OPEN_NOTEBOOKS = "OPEN_NOTEBOOKS";
export const LOAD_NOTEBOOK = "LOAD_NOTEBOOK";
export const LOAD_SAVED_NOTEBOOKS = "LOAD_SAVED_NOTEBOOKS";

// Notebook's section groups
export const UPDATE_NOTEBOOK_SECTION_GROUPS = "UPDATE_NOTEBOOK_SECTION_GROUPS"; // update a notebook's section groups

// Notebook order
export const UPDATE_NOTEBOOK_ORDER = "UPDATE_NOTEBOOK_ORDER";

// Selected Nav
export const UPDATE_SELECTED_NOTEBOOK = "UPDATE_SELECTED_NOTEBOOK";
export const CLOSE_NOTEBOOK = "CLOSE_NOTEBOOK"; // in general

// Loading notebooks
export const TOTAL_NOTEBOOK_LENGTH = "TOTAL_NOTEBOOK_LENGTH";
export const REMOVE_ONE_NOTEBOOK_LENGTH = "REMOVE_ONE_NOTEBOOK_LENGTH"
export const LOAD_NOTEBOOKS_INTO_REDUX = "LOAD_NOTEBOOKS_INTO_REDUX";

// Section groups
export const GET_SECTION_GROUPS = "GET_SECTION_GROUPS";
export const LOAD_SECTION_GROUPS = "LOAD_SECTION_GROUPS";
export const LOAD_SAVED_SECTION_GROUPS = "LOAD_SAVED_SECTION_GROUPS";
export const LOAD_SAVED_SECTION_GROUPS_INTO_REDUX = "LOAD_SAVED_SECTION_GROUPS_INTO_REDUX";
